apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: tfc-taskrun
  namespace: mlperf
spec:
  taskRef:
    name: tfc-benchmark
  serviceAccount: mlperf
  inputs:
    resources:
      - name: image
        resourceRef:
          name: tfc-build-image
      - name: source
        resourceRef:
          name: tfc-repo
    params:
      - name: device
        value: "gpu"
      - name: num_gpus
        value: "4"
      - name: batch_size
        value: "200"
      - name: model
        value: "resnet50"
      - name: variable_update
        value: "independent"
      - name: data_format
        value: "NHWC"
      - name: weight_decay
        value: "1e-4"
      - name: optimizer
        value: "momentum"
      - name: gradient_repacking
        value: "8"
      - name: train_dir
        value: "/train"
