apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: tfc-buildah-run
  namespace: mlperf
spec:
  taskRef:
    name: tfc-buildah
  serviceAccount: mlperf
  inputs:
    resources:
      - name: source
        resourceRef:
          name: tfc-repo
  outputs:
    resources:
      - name: image
        resourceRef:
          name: tfc-build-image
