apiVersion: tekton.dev/v1alpha1
kind: TaskRun
metadata:
  name: tfc-buildah-run
  namespace: mlperf
spec:
  taskRef:
    name: tfc-buildah
  serviceAccount: mlperf
  inputs:
    params:
      - name: DOCKERFILE
        value: ./tf_cnn/Dockerfile.centos7 #for ubi7 entitled builds are needed.
    resources:
      - name: source
        resourceRef:
          name: tfc-dockerfile-repo
  outputs:
    resources:
      - name: image
        resourceRef:
          name: tfc-build-image
