---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tfc-repo
spec:
  type: git
  params:
    - name: url
      value: https://github.com/tensorflow/benchmarks.git
    - name: revision
      value: master
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tfc-dockerfile-repo
spec:
  type: git
  params:
    - name: url
      value: https://github.com/AICoE/benchmarks-tekton.git
    - name: revision
      value: tf-cnn
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tfc-build-image
spec:
  type: image
  params:
    - name: url
      value: docker-registry.default.svc:5000/mlperf/tfc-benchmark
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: tfc-build-image-4x
spec:
  type: image
  params:
    - name: url
      value: image-registry.openshift-image-registry.svc:5000/mlperf/tfc-benchmark
