apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  generateName: tf-cnn-pipelinerun-4x-gpu-
spec:
  serviceAccountName: mlperf
  pipelineRef:
    name: tf-cnn-4x
  resources:
  - name: dockerfile-repo
    resourceRef:
      name: tfc-dockerfile-repo
  - name: benchmark-repo
    resourceRef:
      name: tfc-repo
  - name: build-image
    resourceRef:
      name: tfc-build-image-4x-gpu
  params:
  - name: device
    value: "gpu"
  - name: num_gpus
    value: "4"
  - name: batch_size
    value: "200"
  - name: model
    value: "resnet50"
  - name: variable_update
    value: "independent"
  - name: data_format
    value: "NHWC"
  - name: weight_decay
    value: "1e-4"
  - name: optimizer
    value: "momentum"
  - name: gradient_repacking
    value: "8"
  - name: train_dir
    value: "/train"
  - name: dockerfile
    value: ./tf_cnn/Dockerfile.centos7gpu
  - name: build_name
    value: tf-cnn-benchmark-build-4x
