apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: tf-cnn-pipeline-run
spec:
  serviceAccount: mlperf
  pipelineRef:
    name: tf-cnn
  resources:
  - name: dockerfile-repo
    resourceRef:
      name: tfc-dockerfile-repo
  - name: benchmark-repo
    resourceRef:
      name: tfc-repo
  - name: build-image
    resourceRef:
      name: tfc-build-image
  params:
  - name: device
    value: "cpu"
  - name: batch_size
    value: "10"
  - name: model
    value: "resnet50"
  - name: variable_update
    value: "independent"
  - name: data_format
    value: "NHWC"
  - name: weight_decay
    value: "1e-4"
  - name: optimizer
    value: "momentum"
  - name: gradient_repacking
    value: "8"
  - name: train_dir
    value: "/train"
  - name: dockerfile
    value: ./tf_cnn/Dockerfile.centos7
